### ISSUE TITLE
Refactor UIActivityViewController

### ISSUE THREAD

**Issue by amiantos** [amiantos/gamebookengine#4]
https://contagious.dev/blog/faster-uiactivityviewcontroller-share-sheets-with-uiactivityitemprovider/?utm_campaign=iOS%2BDev%2BWeekly&utm_medium=web&utm_source=iOS%2BDev%2BWeekly%2BIssue%2B425

**Comment by jerryturcios08** [comment]
This issue has been resolved by pull request #11.
